require "setting"
require "plugin"
require "p-treesitter"
require "p-lsp"
require "p-colorscheme"
require "p-completion"
require "p-telescope"
require "p-autopair"
require "p-lualine"
require "p-nvim-tree"
require "p-bookmark"
require "p-toogleterm"
-- require "p-ufo"
require "keymap"
require "autocmd"
